
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
    command: >
      /bin/sh -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py createhorillauser --first_name admin --last_name admin --username admin --password admin --email admin@example.com --phone 1234567890 &&
      gunicorn --bind 0.0.0.0:8000 horilla.wsgi:application"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: horilla-db
    restart: unless-stopped
    user: postgres
    volumes:
      - horilla-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=horilla
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  horilla-data: